name = "mc-qqbot"
main = "worker.js"
compatibility_date = "2024-01-01"

# 环境变量
[vars]
PYTHON_SCRIPT = "main.py"

# 构建命令
[build]
command = """
pip install -r requirements.txt
export CLOUDFLARE_API_TOKEN="$CF_API_TOKEN" && \
npm install && \
npx wrangler deploy
"""

# Node.js 版本
[build.env]
NODE_VERSION = "18"

# 文件规则
[[rules]]
type = "ESModule"
globs = ["**/*.js"]

[[build.upload]]
type = "worker"
name = "mc-qqbot"
main = "main.py"

[build.processing]
skip_build = false 