name = "mc-qqbot"
main = "worker.js"
compatibility_date = "2024-01-01"

[vars]
PYTHON_SCRIPT = "main.py"

[[rules]]
type = "ESModule"
globs = ["**/*.js"]

[build]
command = "pip install -r requirements.txt"

[[build.upload]]
type = "worker"
name = "mc-qqbot"
main = "main.py"

[build.processing]
skip_build = false 